### ISSUE TITLE
422 Unprocessable Entity [ 422 ]

### ISSUE THREAD

**Issue by Azaretdodo** [shirkdog/pulledpork#319] opened 2018-10-18 16:31 UTC
Hello,

I have this error when I do this command line :

`./pulledpork.pl` -c pulledpork.conf -i disablesid.conf -T -H

Option H requires an argument

Checking latest MD5 for snortrules-snapshot-29120.tar.gz....
Error downloading https://www.snort.org/rules/snortrules-snapshot-29120.tar.gz.md5?oinkcode="my oinkcode": 422 Unprocessable Entity [ 422 ]``

Thank you in advance to help me to repair this error

Regards.

Dorian ROSSE.

**Comment by Azaretdodo** [comment] 2018-10-19 13:50
I have the same error which the 29111 also how to ask to Thalos for repair this problem ?

Thank you in advance to answer my ask,

Regards.


Dorian ROSSE.

________________________________
De : Shirkdog <notifications@github.com>
Envoyé : Friday, October 19, 2018 3:43:42 PM
À : shirkdog/pulledpork
Cc : Azaretdodo; Author
Objet : Re: [shirkdog/pulledpork] 422 Unprocessable Entity [ 422 ] (#319)


Check to see if rule URL for 29111 works, if so, might have to check with Talos folks, sometimes the md5 is not available on the site.

**Comment by Azaretdodo** [comment] 2018-10-19 15:54
Have you try to answer that if I wait 30 day I will can use my oinkcode which pulledpork ?

how to check if in 30 days that will works these rules in pulledpork ?

Thank you in advance to lighter me,

Regards.


Dorian ROSSE.

________________________________
De : Shirkdog <notifications@github.com>
Envoyé : Friday, October 19, 2018 4:23:09 PM
À : shirkdog/pulledpork
Cc : Azaretdodo; Author
Objet : Re: [shirkdog/pulledpork] 422 Unprocessable Entity [ 422 ] (#319)


This works for me, so there may be an issue with your oinkcode. Also you will not be able to use 2.9.12.0 signatures until the 30 day window has expired if you are only a registered user.

**Comment by finchy** [comment] 2018-10-19 15:57
You haven't needed to "wait 30 days" in about 5 years.

29120 works fine and 29111 works fine.  Not sure what the issue is. 

422 means you are either requesting a file that doesn't exist or your oinkcode is wrong.  Are you replacing "my oinkcode" in the URL with your actual oinkcode?

**Comment by Azaretdodo** [comment] 2018-10-19 15:59
Yes I place the oinkcode from my snort account !

But why that doesn’t works for me ☹ ?

Than you in advance to help me,

Regards.


Dorian ROSSE.

________________________________
De : Joel Esler <notifications@github.com>
Envoyé : Friday, October 19, 2018 5:57:20 PM
À : shirkdog/pulledpork
Cc : Azaretdodo; Author
Objet : Re: [shirkdog/pulledpork] 422 Unprocessable Entity [ 422 ] (#319)


You haven't needed to "wait 30 days" in about 5 years.

29120 works fine and 29111 works fine. Not sure what the issue is.

422 means you are either requesting a file that doesn't exist or your oinkcode is wrong. Are you replacing "my oinkcode" in the URL with your actual oinkcode?

**Comment by Azaretdodo** [comment] 2018-10-19 16:03
That the line I modified on the pulledpork.conf file :

rule_url=https://www.snort.org/reg-rules/|snortrules-snapshot-29111.tar.gz|(here my oinkcode)

Have I bad modified my pulledpork.conf file ?

Thank you in advance to lighter me,

Regards.


Dorian ROSSE.

________________________________
De : Dorian ROSSE <dorianbrice@hotmail.fr>
Envoyé : Friday, October 19, 2018 5:59:39 PM
À : shirkdog/pulledpork
Objet : RE: [shirkdog/pulledpork] 422 Unprocessable Entity [ 422 ] (#319)

Yes I place the oinkcode from my snort account !

But why that doesn’t works for me ☹ ?

Than you in advance to help me,

Regards.


Dorian ROSSE.

________________________________
De : Joel Esler <notifications@github.com>
Envoyé : Friday, October 19, 2018 5:57:20 PM
À : shirkdog/pulledpork
Cc : Azaretdodo; Author
Objet : Re: [shirkdog/pulledpork] 422 Unprocessable Entity [ 422 ] (#319)


You haven't needed to "wait 30 days" in about 5 years.

29120 works fine and 29111 works fine. Not sure what the issue is.

422 means you are either requesting a file that doesn't exist or your oinkcode is wrong. Are you replacing "my oinkcode" in the URL with your actual oinkcode?

**Comment by finchy** [comment] 2018-10-19 16:04
I just looked at the logs for snort.org and I see a successful download for 29120 with your oinkcode yesterday at 16:44 GMT.

**Comment by finchy** [comment] 2018-10-19 16:05
I also don't see any further attempts since.

**Comment by Azaretdodo** [comment] 2018-10-19 16:08
Joel please can you answer to me if my line modified on pulledpork.conf is good ?

rule_url=https://www.snort.org/reg-rules/|snortrules-snapshot-29111.tar.gz|(here my oinkcode)

I tried which the snort 29111 and 29120 but all failed… ☹

Thank you in advance to lighter me,

Regards.


Dorian ROSSE.

________________________________
De : Joel Esler <notifications@github.com>
Envoyé : Friday, October 19, 2018 6:05:13 PM
À : shirkdog/pulledpork
Cc : Azaretdodo; Author
Objet : Re: [shirkdog/pulledpork] 422 Unprocessable Entity [ 422 ] (#319)


I also don't see any further attempts since.

**Comment by finchy** [comment] 2018-10-19 16:11
Should look something liked his:

`rule_url=https://www.snort.org/reg-rules/|snortrules-snapshot.tar.gz|<oinkcode>`

Are you failing an SSL negotiation?  how about running pulledpork with `-vvv` as an argument and giving us the output?

**Comment by Azaretdodo** [comment] 2018-10-19 16:17
I when to try as you can read :

root@bitfenix-server:/pulledpork# pulledpork -vvv
pulledpork: command not found
root@bitfenix-server:/pulledpork# ./pulledpork -vvv
-bash: ./pulledpork: No such file or directory
root@bitfenix-server:/pulledpork# .\pulledpork -vvv
.pulledpork: command not found


what you try to tell me ?

Run the command Following which your -vvv options ? :

./pulledpork.pl -c pulledpork.conf -i disablesid.conf -T -H


Thank you in advance to help me,

Regards.


Dorian ROSSE.

De : Joel Esler<mailto:notifications@github.com>
Envoyé le :vendredi 19 octobre 2018 18:11
À : shirkdog/pulledpork<mailto:pulledpork@noreply.github.com>
Cc : Azaretdodo<mailto:dorianbrice@hotmail.fr>; Author<mailto:author@noreply.github.com>
Objet :Re: [shirkdog/pulledpork] 422 Unprocessable Entity [ 422 ] (#319)


Should look something liked his:

rule_url=https://www.snort.org/reg-rules/|snortrules-snapshot.tar.gz|<oinkcode>

Are you failing an SSL negotiation? how about running pulledpork with -vvv as an argument and giving us the output?

**Comment by Azaretdodo** [comment] 2019-01-22 09:12
I went to put all files from pulledpork at the pulledpork folder then I launch this command line :

./pulledpork.pl -o /usr/local/etc/snort/rules/ -O 'my_oinkcode’ -c pulledpork.conf -D ubuntu-18-04 -u https://www.snort.org/rules/snortrules-snapshot-29120.tar.gz -i disablesid.conf -T -H

the shell answer this :

You need to define an oinkcode, please review the rule_url section of the pulledpork config file!
at ./pulledpork.pl line 2101.

the nano program doesn’t want to works which the ctrl + underscore also I don’t know how to put the oinkcode where It asked ☹,

Thank you in advance to help me for put the oinkcode where It asked,

Regards.


Dorian ROSSE.

________________________________
De : Joel Esler <notifications@github.com>
Envoyé : Tuesday, January 22, 2019 2:27:47 AM
À : shirkdog/pulledpork
Cc : Azaretdodo; Author
Objet : Re: [shirkdog/pulledpork] 422 Unprocessable Entity [ 422 ] (#319)


root@bitfenix-server:/pulledpork# pulledpork -vvv pulledpork: command not found root@bitfenix-server:/pulledpork# ./pulledpork -vvv -bash: ./pulledpork: No such file or directory root@bitfenix-server:/pulledpork# .\pulledpork -vvv .pulledpork: command
 not found

This tells me that you're running it wrong, or it's not executable.

**Comment by Asky-M** [comment] 2020-07-29 07:17
i think this error because md5 not match or not found. today, i trying to use snortrules-snapshot-3000.tar.gz and i found same error. when i check sums on https://www.snort.org/downloads/registered/md5s, file snortrules-snapshot-3000.tar.gz not found md5 hash and then i change snort version to snortrules-snapshot-2983.tar.gz after that i running again command pulledpork.pl -c /usr/local/etc/snort/pulledpork.conf and solved to me. 

sorry for my english.

**Comment by shirkdog** [comment] 2020-08-26 19:21
Closing this issue, preparing to tag 0.7.4 so verify if the latest version works for you.

**Closed by shirkdog** 2020-08-26 19:21 UTC

**Comment by frpr00** [comment] 2021-11-27 20:19
Hi everybody. I have the same problem. Tell me the solution, please.
(Version of my snort 3.1.17, pulledpork - 0.8.0)

**Comment by finchy** [comment] 2021-11-27 22:21
422 means the file you are attempting to doesn’t exist.

**Comment by frpr00** [comment] 2021-11-27 22:31
I understand this, it checks everything according to the latest MD5 31170, it is not in MD5. But I don't understand what to do with it. 
Я ведь все обновила даже, почему оно ищет то, чего нет.

This is my 19 string:  rule_url=https://www.snort.org/rules/|snortrules-snapshot.tar.gz|<oinkcode>, with my oinkcode

**Comment by frpr00** [comment] 2021-11-27 22:34
Сорян за российский

**Comment by KwokBiao** [comment] 2022-03-30 15:52
1. This may be because the snort official did not upload the MD5 in time, resulting in the absence of the inspection file;

2. The Asky-M method is very direct and effective, browse https://www.snort.org/downloads/registered/md5s to find the latest compressed package, such as snortrules-snapshot-31210.tar.gz

3. Modify rule_url=https://www.snort.org/rules/|snortrules-snapshot-31210.tar.gz|oinkcode in the configuration file

The above method is still valid in PulledPork v0.8.0 and Snort++ 3.1.25.0.   @frpr00   @Asky-M Thansk for your

**Comment by finchy** [comment] 2022-03-30 15:54
Md5 is created on upload, so 1 isn't possible.

**Comment by Azaretdodo** [comment] 2022-03-30 19:45
Hello cat and Joel,


I don't find this problem on the fork pulledpork thus I don't find if I was happening error 422 or error one,

Thanks you in advance for your time,

Regards.


Azaretdodo.
________________________________

**Comment by finchy** [comment] 2022-03-30 19:47
422 has nothing to do with pulledpork.  422 is an error code from the website that says you’re requesting a version of the Snort ruleset that doesn’t exist.

**Comment by Azaretdodo** [comment] 2022-03-30 19:49
Ok thanks you Joel,

Have a nice evening from the France this is twenty two to eleven of the night here,

Regards.


Azaretdodo.
________________________________
