### ISSUE TITLE
rule upgrade halts

### ISSUE THREAD

**Issue by topeminent** [shirkdog/pulledpork#278] opened 2017-07-29 15:22 UTC
I installed pulledpork on ubuntu 14.04 but upgrading the rules won t work . I get the following error 

Checking latest MD5 for opensource.tar.gz....
        A 404 error occurred, please verify your filenames and urls for your tarball!
        Error 404 when fetching https://snort.org/downloads/community/opensource.tar.gz.md5 at /usr/local/bin/pulledpork.pl line 546.
No such file or directory at /usr/local/bin/pulledpork.pl line 550.
readline() on closed filehandle FILE at /usr/local/bin/pulledpork.pl line 552.
Use of uninitialized value $md5 in scalar chomp at /usr/local/bin/pulledpork.pl line 553.
Use of uninitialized value $md5 in pattern match (m//) at /usr/local/bin/pulledpork.pl line 555.
Rules tarball download of opensource.tar.gz....
        A 404 error occurred, please verify your filenames and urls for your tarball!

How can i fix this problem ?

**Comment by shirkdog** [comment] 2017-07-29 15:32
This is a duplicate of #277 which is now resolved in the main repo.

**Closed by shirkdog** 2017-07-29 15:32 UTC
