### ISSUE TITLE
how to resolve No Match?

### ISSUE THREAD

**Issue by GooseSteps** [shirkdog/pulledpork#350] opened 2020-11-04 08:29 UTC
Checking latest MD5 for snortrules-snapshot-29161.tar.gz....
	No Match
	Done
Rules tarball download of snortrules-snapshot-29161.tar.gz....
	No Match
	Done
Rules tarball download of snortrules-snapshot-29161.tar.gz....
Error downloading https://www.snort.org/rules/snortrules-snapshot-29161.tar.gz?oinkcode=c2e105771de1fb1f9380bf4aa4b38c89a6277664: 500 Can't connect to www.snort.org:443 (Name or service not known) [ 500 ]

**Comment by finchy** [comment] 2020-11-04 14:28
Duplicate of #349

**Closed by finchy** 2020-11-04 14:28 UTC
