### ISSUE TITLE
success to set up the oinkcode at line 2101 and too the base url but It failed wich a lot of error code

### ISSUE THREAD

**Issue by Azaretdodo** [shirkdog/pulledpork#327] opened 2019-05-04 16:29 UTC
hello,

I launch this command line :

**nano +2101 pulledpork.pl**

finally a lot or errors code as follow :

**./pulledpork.pl -o /usr/local/etc/snort/rules/ -c pulledpork.conf -D ubuntu-18-04 -u https://www.snort.org/rules/snortrules-snapshot-29120.tar.gz -i disablesid.conf -T -H
Bareword found where operator expected at ./pulledpork.pl line 2100, near "29130.tar"
        (Missing operator before tar?)
Found = in conditional, should be == at ./pulledpork.pl line 2104.
Global symbol "$_My_OinkCode" requires explicit package name (did you forget to declare "my $_My_OinkCode"?) at ./pulledpork.pl line 2100.
syntax error at ./pulledpork.pl line 2100, near ""my $_My_OinkCode"("
Global symbol "$base_url" requires explicit package name (did you forget to declare "my $base_url"?) at ./pulledpork.pl line 2100.
Unknown regexp modifier "/w" at ./pulledpork.pl line 2100, at end of line
Unknown regexp modifier "/w" at ./pulledpork.pl line 2100, at end of line
Unknown regexp modifier "/w" at ./pulledpork.pl line 2100, at end of line
Global symbol "$base_url" requires explicit package name (did you forget to declare "my $base_url"?) at ./pulledpork.pl line 2106.
syntax error at ./pulledpork.pl line 2106, near "https:"
Unknown regexp modifier "/w" at ./pulledpork.pl line 2106, at end of line
Unknown regexp modifier "/w" at ./pulledpork.pl line 2106, at end of line
./pulledpork.pl has too many errors.**

Thank you in advance to help to edit this pulledpork file,

Regards.

Dorian ROSSE.

**Comment by shirkdog** [comment] 2020-08-26 19:30
Closing this and assuming the issue is no longer happening, if that is not the case, please reopen. We need to add error handling for missing items, but normally these types of errors are missing information like the Oinkcode, or if you may have been looking for signatures from one version of Snort, while you have another version of Snort installed.

**Closed by shirkdog** 2020-08-26 19:30 UTC
