### ISSUE TITLE
Writing to multiple rules files results in duplicate rules

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shirkdog/pulledpork#138] opened 2015-04-23 15:12 UTC
```
What steps will reproduce the problem?
1. Run pulledpork as normal with the '-k' flag.
2. Immediately run pulledpork using '-k -P' flags.

What is the expected output? What do you see instead?
The expectation is that the output directory will be identical after each run. 
Instead a duplicate entry is added for each rule. 

For example, my config includes both the VRT and the ET sets. If I run an 
update and capture the line count of the rules files....

/usr/bin/pulledpork.pl -S 2.9.5.3 -c /etc/pulledpork/pulledpork.conf -k -T -P > 
/dev/null 2>&1 && wc -l /tmp/snortrules/*.rules | grep total
   37727 total
/usr/bin/pulledpork.pl -S 2.9.5.3 -c /etc/pulledpork/pulledpork.conf -k -T -P > 
/dev/null 2>&1 && wc -l /tmp/snortrules/*.rules | grep total
   74659 total
/usr/bin/pulledpork.pl -S 2.9.5.3 -c /etc/pulledpork/pulledpork.conf -k -T -P > 
/dev/null 2>&1 && wc -l /tmp/snortrules/*.rules | grep total
   111603 total

Manually inspecting a file I can see that each run results in each signature 
being duplicated at each update.

What version of the product are you using? On what operating system?

Pulled Pork 0.7.0 on RHEL 6.4

Please provide any additional information below.

This is new behavior with 0.7.0. I was using the same configuration with 0.6.2 
without the duplication.
```

Original issue reported on code.google.com by `scott.p...@gmail.com` on 13 Sep 2013 at 3:24

**Comment by notnyt** [comment] 2016-02-06 12:47
This is caused by the following line in read_rules, which is called twice if keep files and log sid changes are set.
````
                            push @ {$categories->{$file}{trim($gid)}},($sid);
````
Easy fix...
https://github.com/notnyt/pulledpork/commit/ea8b7776e86140e68a91943e62f585a2ed4d0867

**Comment by shirkdog** [comment] 2017-12-06 15:21
Code has changed and should be addressed in current release.

**Closed by shirkdog** 2017-12-06 15:21 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
