### ISSUE TITLE
Rules with a : in the msg

### ISSUE THREAD

**Issue by DigiAngel** [shirkdog/pulledpork#266] opened 2017-05-26 13:58 UTC
So [suspect networks](https://suspect-networks.io/downloads/suspect_networks.rules) has a great ruleset.  Looking at it, the msg portion contains:
~~~
msg:"SN: Inbound TCP traffic from suspect network (AS14576 - US)"
~~~
~~~
alert tcp 104.193.252.128/26 any -> $HOME_NET any (msg:"SN: Inbound TCP traffic from suspect network (AS14576 - US)"; flags:S; reference:url,https://suspect-networks.io/networks/cidr/29/; threshold: type limit, track by_dst, seconds 30, count 1; classtype:misc-attack; sid:71910029; rev:1;)
~~~

It looks like the : tweaks out PP and in sid-msg.map we get:
~~~
71910029 || SN || url,https
~~~
Currently my quick workaround is to change the : to _ after dl in the update script:
~~~
/usr/bin/wget https://suspect-networks.io/downloads/suspect_networks.rules -O /tmp/suspect_networks.rules
/bin/cat /tmp/suspect_networks.rules | sed 's/SN: /SN_/' > /opt/etc/snort/rules/suspect_networks.rules
~~~
For reference:  [py-idstools #51](https://github.com/jasonish/py-idstools/issues/51) just thought you might want to take a peak at it.  Thank you.

**Comment by shirkdog** [comment] 2017-10-14 18:01
Closing this issue as a duplicate of #283 and we will use that issue to discus an approach forward.

**Closed by shirkdog** 2017-10-14 18:01 UTC
